image: docker:latest
services:
- docker:dind

stages:
- build
- release

variables:
  DOCKER_REGISTRY: registry.gitlab.com
  DOCKER_REGISTRY_IMAGE: $DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  CONTAINER_BUILD_IMAGE: $DOCKER_REGISTRY_IMAGE:$CI_BUILD_REF
  CONTAINER_RELEASE_IMAGE: $DOCKER_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  CONTAINER_LATEST_IMAGE: $DOCKER_REGISTRY_IMAGE:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY

build-image:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_BUILD_IMAGE .
    - docker push $CONTAINER_BUILD_IMAGE

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_BUILD_IMAGE
    - docker tag $CONTAINER_BUILD_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE

release-latest-image:
  stage: release
  script:
    - docker pull $CONTAINER_BUILD_IMAGE
    - docker tag $CONTAINER_BUILD_IMAGE $CONTAINER_LATEST_IMAGE
    - docker push $CONTAINER_LATEST_IMAGE
  only:
    - master