image: docker:latest
services:
- docker:dind

stages:
- build
- release

variables:
  CONTAINER_BUILD_IMAGE: $CI_REGISTRY_IMAGE:$CI_BUILD_REF
  CONTAINER_LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build-image:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_BUILD_IMAGE .
    - docker push $CONTAINER_BUILD_IMAGE

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_BUILD_IMAGE
    - docker tag $CONTAINER_BUILD_IMAGE $CI_REGISTRY_IMAGE:${CI_BUILD_REF_NAME//\//_}
    - docker push $CI_REGISTRY_IMAGE:${CI_BUILD_REF_NAME//\//_}

release-latest-image:
  stage: release
  script:
    - docker pull $CONTAINER_BUILD_IMAGE
    - docker tag $CONTAINER_BUILD_IMAGE $CONTAINER_LATEST_IMAGE
    - docker push $CONTAINER_LATEST_IMAGE
  only:
    - master